services:
  root-node:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: esp-root
    environment:
      - NODE_TYPE=root
      - NODE_ID=1
      - ROUTER_SSID=TestRouter
      - ROUTER_PASSWORD=TestPassword123
      - MESH_PASSWORD=MeshNetwork123
      - MESH_CHANNEL=1
    networks:
      mesh-net:
        ipv4_address: 192.168.100.2
    restart: on-failure
    tty: true
    stdin_open: true

  node-2:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: esp-node-2
    environment:
      - NODE_TYPE=internal
      - NODE_ID=2
      - ROUTER_SSID=TestRouter
      - ROUTER_PASSWORD=TestPassword123
      - MESH_PASSWORD=MeshNetwork123
      - MESH_CHANNEL=1
    networks:
      mesh-net:
        ipv4_address: 192.168.100.3
    depends_on:
      - root-node
    restart: on-failure
    tty: true
    stdin_open: true

  node-3:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: esp-node-3
    environment:
      - NODE_TYPE=internal
      - NODE_ID=3
      - ROUTER_SSID=TestRouter
      - ROUTER_PASSWORD=TestPassword123
      - MESH_PASSWORD=MeshNetwork123
      - MESH_CHANNEL=1
    networks:
      mesh-net:
        ipv4_address: 192.168.100.4
    depends_on:
      - root-node
    restart: on-failure
    tty: true
    stdin_open: true

networks:
  mesh-net:
    name: esp-mesh-network
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
          gateway: 192.168.100.1
