name: ESP-IDF Build

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: 
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 0 
        
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.1
        target: esp32
        
    - name: Archive firmware artifacts
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: |
          build/data_exchange_system.bin
          build/partition_table/partition-table.bin
          build/bootloader/bootloader.bin
